src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CarRepository::class)]
#[ORM\HasLifecycleCallbacks()]
class Car
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $brand;

    #[ORM\Column(type: 'string', length: 255)]
    private $model;

    #[ORM\Column(type: 'string', length: 255)]
    private $reg_number;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    #[ORM\OneToMany(mappedBy: 'car', targetEntity: Refuelling::class)]
    private $refuellings;

    public function __construct()
    {
        $this->refuellings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getRegNumber(): ?string
    {
        return $this->reg_number;
    }

    public function setRegNumber(string $reg_number): self
    {
        $this->reg_number = $reg_number;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        $this->createdAt = new \DateTimeImmutable('now');
    }

    /**
     * @return Collection|Refuelling[]
     */
    public function getRefuellings(): Collection
    {
        return $this->refuellings;
    }

    public function addRefuelling(Refuelling $refuelling): self
    {
        if (!$this->refuellings->contains($refuelling)) {
            $this->refuellings[] = $refuelling;
            $refuelling->setCar($this);
        }

        return $this;
    }

    public function removeRefuelling(Refuelling $refuelling): self
    {
        if ($this->refuellings->removeElement($refuelling)) {
            // set the owning side to null (unless already changed)
            if ($refuelling->getCar() === $this) {
                $refuelling->setCar(null);
            }
        }

        return $this;
    }
}

src/Entity/Refuelling.php
<?php

namespace App\Entity;

use App\Repository\RefuellingRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RefuellingRepository::class)]
#[ORM\HasLifecycleCallbacks()]
class Refuelling
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'refuellings')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\ManyToOne(targetEntity: Car::class, inversedBy: 'refuellings')]
    #[ORM\JoinColumn(nullable: false)]
    private $car;

    #[ORM\ManyToOne(targetEntity: PetrolStation::class, inversedBy: 'refuellings')]
    #[ORM\JoinColumn(nullable: false)]
    private $petrolStation;

    #[ORM\ManyToOne(targetEntity: Fuel::class, inversedBy: 'refuellings')]
    #[ORM\JoinColumn(nullable: false)]
    private $fuel;

    #[ORM\Column(type: 'decimal', precision: 6, scale: 2)]
    private $litres;

    #[ORM\Column(type: 'decimal', precision: 7, scale: 2)]
    private $cost;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private $updatedAt;

    #[ORM\ManyToOne(targetEntity: Currency::class, inversedBy: 'refuellings')]
    #[ORM\JoinColumn(nullable: false)]
    private $currency;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCar(): ?Car
    {
        return $this->car;
    }

    public function setCar(?Car $car): self
    {
        $this->car = $car;

        return $this;
    }

    public function getPetrolStation(): ?PetrolStation
    {
        return $this->petrolStation;
    }

    public function setPetrolStation(?PetrolStation $petrolStation): self
    {
        $this->petrolStation = $petrolStation;

        return $this;
    }

    public function getFuel(): ?Fuel
    {
        return $this->fuel;
    }

    public function setFuel(?Fuel $fuel): self
    {
        $this->fuel = $fuel;

        return $this;
    }

    public function getLitres(): ?string
    {
        return $this->litres;
    }

    public function setLitres(string $litres): self
    {
        $this->litres = $litres;

        return $this;
    }

    public function getCost(): ?string
    {
        return $this->cost;
    }

    public function setCost(string $cost): self
    {
        $this->cost = $cost;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    #[ORM\PreUpdate]
    public function setUpdatedAtValue(): void
    {
        $this->updatedAt = $updatedAt;
    }


    public function getCurrency(): ?Currency
    {
        return $this->currency;
    }

    public function setCurrency(?Currency $currency): self
    {
        $this->currency = $currency;

        return $this;
    }
}

src/Form/RefuellingType.php
<?php

namespace App\Form;

use App\Entity\Refuelling;
use App\Entity\Car;
use App\Entity\Fuel;
use App\Entity\PetrolStation;
use App\Entity\Currency;
use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class RefuellingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('car', EntityType::class, [
                'label' => 'Автомобиль',
                'class' => Car::class,
                'placeholder' => 'Выберите автомобиль',
                //'required' => false,
                //'choice_label' => 'reg_number',
                'choice_label' => function ($car) {
                    return $car->getBrand() .' '. $car->getModel() .' - '. $car->getRegNumber();
                }
            ])
            ->add('fuel', EntityType::class, [
                'label' => 'Вид топлива',
                'class' => Fuel::class,
                'choice_label' => 'type'
            ])
            ->add('petrolStation', EntityType::class, [
                'label' => 'Заправка',
                'placeholder' => 'Выберите станцию',
                'class' => PetrolStation::class,
                'choice_label' => 'name'
            ])
            ->add('litres', null, [
                'label' => 'Литры',
            ])
            ->add('cost', null, [
                'label' => 'Полная стоимость',
            ])
            ->add('currency', EntityType::class, [
                'label' => 'Валюта',
                'class' => Currency::class,
                'choice_label' => 'name'
            ])
            ->add('createdAt', null, [
                'label' => 'Время заправки',
                'with_seconds' => false,
                //'format' => 'yyyy-MM-dd HH:mm',
                'widget' => 'single_text',
                'html5' => true,
                'attr' => ['class' => 'js-datepicker']
            ])
            ->add('Save', SubmitType::class, [
                'label' => 'Отправить'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Refuelling::class,
        ]);
    }
}

src/Controller/RefuellingController.php
<?php

namespace App\Controller;

use App\Entity\Refuelling;
use App\Repository\RefuellingRepository;
use App\Form\RefuellingType;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\Validator\Constraints as Assert;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

#[IsGranted("ROLE_USER")]
class RefuellingController extends AbstractController
{
    private $refuellingRepo;
    private $doctrine;

    public function __construct(RefuellingRepository $refuellingRepo, ManagerRegistry $doctrine)
    {
        $this->refuellingRepo = $refuellingRepo;
        $this->doctrine = $doctrine;
    }
    
    #[Route('/', name: 'homepage')]
    public function showAllRecords(Request $request): Response
    {
        $offset = max(0, $request->query->getInt('offset', 0));
        $paginator = $this->refuellingRepo->getRefuellingPaginator($offset);

        return $this->render('refuelling/index.html.twig', [
            'title' => 'Записи',
            'records' => $paginator,
            'previous' => $offset - RefuellingRepository::PAGINATOR_PER_PAGE,
            'next' => min(count($paginator), $offset + RefuellingRepository::PAGINATOR_PER_PAGE),
            'add_record' => false,
            'form' => null,
        ]);
    }

    #[Route('/refuellings/my', name: 'my_fuellings')]
    public function showMyRecords(Request $request): Response
    {
        $offset = max(0, $request->query->getInt('offset', 0));
        $paginator = $this->refuellingRepo->getRefuellingPaginator($offset);

        return $this->render('refuelling/index.html.twig', [
            'title' => 'Записи',
            'records' => $paginator,
            'previous' => $offset - RefuellingRepository::PAGINATOR_PER_PAGE,
            'next' => min(count($paginator), $offset + RefuellingRepository::PAGINATOR_PER_PAGE),
            'add_record' => true,
            'form' => null,
        ]);
    }

    #[Route('/refuelling/add', name: 'add_refuelling')]
    public function add_refuelling(Request $request): Response
    {
        
        $record = new Refuelling();
        $record->setUser($this->getUser());
        $record->setCreatedAt(new \DateTimeImmutable('now'));
        
        $form = $this->createForm(RefuellingType::class, $record);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $record = $form->getData();

            $entityManager = $this->doctrine->getManager();
            $entityManager->persist($record);
            $entityManager->flush();

            return $this->redirectToRoute('refuelling_success');
        }

        return $this->renderForm('refuelling/index.html.twig', [
            'form' => $form,
            'records' => [],
            'add_record' => false,
            'back' => true,
        ]);
    }

    #[Route('refuelling/edit/{id}', name: 'edit_refuelling')]
    public function editRefuelling(Request $request, ?int $id = null)
    {
        $record = $this->refuellingRepo->find($id);

        if(!$record)
        {
            throw $this->createNotFoundException(
                'No record found for id '. $id
            );
        }

        if($record->getUser() !== $this->getUser())
        {
            throw $this->createAccessDeniedException();
        }

        $form = $this->createForm(RefuellingType::class, $record);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $record = $form->getData();

            $entityManager = $this->doctrine->getManager();
            $entityManager->persist($record);
            $entityManager->flush();

            return $this->redirectToRoute('refuelling_success');
        }

        return $this->renderForm('refuelling/index.html.twig', [
            'form' => $form,
            'records' => [],
            'add_record' => false,
            'back' => true,
        ]);
    }

    #[Route('/refuelling/success', name: 'refuelling_success')]
    public function refuelling_success(): Response
    {
        $message = 'Запись о заправке успешно сохранена';
        
        return $this->render('refuelling/success.html.twig', [
            'title' => 'Сохранено',
        ]);
    }

    #[Route('/me', name: 'my_name')]
    public function getMyName()
    {
        $user = $this->getUser();
        if($user instanceof User)
        {
            return $this->json([
                $user->getName(),
            ]);
        }

        return $this->json(
            null, 401
        );
    }
}

templates/refuelling/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Главная{% endblock %}

{% block stylesheets %}
  {{ parent() }}
  <link href="{{ asset('css/refuelling.css') }}" rel="stylesheet">
{% endblock %}

{% block javascripts %}
  {{ parent() }}
{% endblock %}

{% block content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-middle pt-3 mb-3 border-bottom">
  {% if add_record %}
  <h4> <a href="{{ path('add_refuelling') }}"> Добавить запись...</a> </h4>
  {% endif %}
  
  {% if back is defined %}
    <p> <a href="{{ path('homepage') }}"> назад </a></p>
  {% endif %}

  {#
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group me-2">
        <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
        <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
      </div>
      <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
        <span data-feather="calendar"></span>
        This week
      </button>
    </div>
  #}
</div>

{# если есть записи, показываем таблицу #} 
{% if records|length > 0 %}

<h6 class='mb-2'>Всего {{ records|length }} записей о заправках автомобилей</h6>

<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">Дата</th>
        <th scope="col">Время</th>
        <th scope="col">Пользователь</th>
        <th scope="col">Автомобиль</th>
        <th scope="col">Топливо</th>
        <th scope="col">Объем, л</th>
        <th scope="col">Сумма чека</th>
        <th scope="col">Цена за литр</th>
        <th scope="col">Станция</th>
        <th scope="col">isOwner</th>
      </tr>
    </thead>
    <tbody>
      {% for record in records|sort %}
      
      <tr>
        <td>{{ record.createdAt|date('Y-m-d') }}</td>
        <td>{{ record.createdAt|date('H:i') }}</td>
        <td>{{ record.user.name }}</td>
        <td>{{ [record.car.brand, ' ', record.car.model, ' - ',record.car.regNumber]|join }}</td>
        <td>{{ record.fuel.type }}</td>
        <td>{{ record.litres|number_format(0) }}</td>
        <td>{{ [record.cost|number_format(0), ' ', record.currency.isoCode]|join }}</td>
        <td>{{ [(record.cost / record.litres)|number_format(1), ' ', record.currency.isoCode]|join }}</td>
        <td>{{ record.petrolStation.name }}</td>
        <td>{{ app.user == record.user }}</td>
      </tr>

      {% endfor %}

    </tbody>
  </table>
</div>

{% if previous >= 0 %}
  <a href="{{ path('homepage', {offset: previous}) }}"> Предыдущие </a>
{% endif %}
{% if next < records|length %}
  <a href="{{ path('homepage', {offset: next}) }}"> Следующие </a>
{% endif %}

{# если нет записей, но есть форма, показываем форму #} 
{% elseif form %}

<div class="container-fluid pt-3">  
  <div class="form-errors">
    {{ form_errors(form) }}
  </div>
  
  {{ form_start(form) }}

  <div class="row border-bottom mt-4 mb-4 pb-3">
    <div class="col-md-6 border-right">
      {{ form_row(form.car) }}
    </div>
    <div class="col-md-3">
      {{ form_row(form.petrolStation) }}
    </div>
    <div class='col-md-3'>
      {{ form_row(form.createdAt) }}
    </div>
  </div>

  <div class="row border-bottom mb-4 pb-3">
    <div class="col-md-3">
    {{ form_row(form.fuel) }}
    </div>
    <div class="col-md-3">
    {{ form_row(form.litres) }}
    </div>
    <div class="col-md-3">
    {{ form_row(form.cost) }}
    </div>
    <div class="col-md-3">
    {{ form_row(form.currency) }}
    </div>
  </div>
  
  <div class="d-flex justify-content-center pt-3">
    {{ form_row(form.Save) }}
  </div>
</div>

  {{ form_end(form) }}

{# вариант в случае отсутствия записей и формы #} 
{% else %}

  <h5>Записей о заправках автомобилей не найдено</h5>

{% endif %}

{# <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> #}

{% endblock %}

templates/refuelling/success.html.twig
{% extends 'layout.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('css/refuelling.css') }}" rel="stylesheet">
{% endblock %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

    <div class="pt-5 text-center">
        <h2>Данные о заправке сохранены</h2>
        <p><a href='{{ path('homepage') }}'>Перейти на главную</a></p>
    </div>

{% endblock %}